Repository ChromeGaming/PACKABUNCHAS, pull requests merged in 2024-06, with the labels that each got.

#62 Fixed spelling mistakes
  README.md
Labels: level1, gssoc

#68 404 not found page added
  404.html
  404pic2.png
Labels: level2, Under Review, gssoc

#76 Added the instructions button
  game.js
  index.html
Labels: level2, gssoc, Approved

#87 sidebar created
  index.html
Labels: level2, gssoc, Approved
