Repository ChromeGaming/PACKABUNCHAS, pull requests merged in 2024-05, with the labels that each got.

#15 Fixed the Title icon issue
  index.html
Labels: Level - 1, GSSoC'24, Approved

#25 canvas border updated
  index.html
Labels: level2, gssoc

#26 Update README.md
  README.md
Labels: level1, gssoc, Approved

#28 Create Contributing.md
  Create Contributing.md
Labels: level1, gssoc, Approved

#32 [New Feature]: Implement Gradient Theme Button
  game.js
  index.html
Labels: level2, gssoc, Need changes
